---
- name: Ensure the nginx is installed
  apt: name=nginx state=latest update_cache=yes

- name: remove nginx default sites
  file: path=/etc/nginx/conf.d/{{ item }} state=absent
  with_items:
    - default.conf
    - ssl.conf
    - virtual.conf

- name: Ensure nginx log directory exist
  file: path=/var/log/nginx state=directory owner=root group=root mode=0755

- name: copy nginx main config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: start nginx on boot
  service: name=nginx enabled=yes state=started
