---
- name: ensure Java is installed
  apt: name=openjdk-7-jre state=present

- name: Ensure the necessary folders exist
  file: dest={{ item }} state=directory
  with_items:
    - /opt/demo-app
    - /var/log/demo-app

- name: download app binaries
  get_url:
    url: https://s3-ap-southeast-2.amazonaws.com/covata-robertbartlett-content-objectdata/spring-boot-sample-jetty-1.0.0.RC5.jar
    dest: /opt/demo-app/demo-app.jar

- name: install supervisord configuration
  copy: src=supervisord.conf dest=/etc/supervisord.d/demo-app.conf owner=root group=root mode=0644
  register: supervisordConf

- name: update supervisord
  command: supervisorctl update
  when: supervisordConf|changed

- name: copy reader site configuration
  copy: src=nginx.conf dest=/etc/nginx/conf.d/demo-app.conf owner=root group=root mode=0644
  register: nginxConf

- name: reload nginx
  service: name=nginx state=reloaded
  when: nginxConf|changed

- name: Allow nginx firewall
  ufw: proto=tcp port=80 rule=allow

# Uncomment in case we later use ssl certificates
# - name: Allow nginx ssl firewall
#   ufw: proto=tcp port=443 rule=allow